export const projects = [
  {
    title: "React Reserve",
    subtitle: "MERN Stack",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolore rerum laborum iure enim sint nemo omnis voluptate exercitationem eius?",
    image: "https://study.com/cimages/videopreview/7m7z42z3x3.jpg",
    link: "https://reactbootcamp.com",
  },
  {
    title: "React Tracks",
    subtitle: "React and Python",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolore rerum laborum iure enim sint nemo omnis voluptate exercitationem eius?",
    image: "https://study.com/cimages/videopreview/7m7z42z3x3.jpg",
    link: "https://reedbarger.com",
  },
  {
    title: "DevChat",
    subtitle: "React and Firebase",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolore rerum laborum iure enim sint nemo omnis voluptate exercitationem eius?",
    image: "https://study.com/cimages/videopreview/7m7z42z3x3.jpg",
    link: "https://jsbootcamp.com",
  },
  {
    title: "Epic Todo App",
    subtitle: "React Hooks",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolore rerum laborum iure enim sint nemo omnis voluptate exercitationem eius?",
    image: "https://study.com/cimages/videopreview/7m7z42z3x3.jpg",
    link: "https://pythonbootcamp.com",
  },
];

export const skills = [
  "JavaScript",
  "React",
  "Next.js",
  "Node",
  "GraphQL",
  "Apollo",
  "MongoDB",
  "Firebase",
  "Python",
  "Django",
  "Flask",
  "TensorFlow",
  "Keras",
  "PyTorch",
  "Pandas",
  "Numpy",
  "Matplotlib",
  "Seaborn",
  "Scikit-Learn",
  "Jupyter",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "NoSQL",
  "REST",
  "APIs",
  "Git",
  "GitHub",
  "HTML",
  "CSS",
  "SASS",
  "Bootstrap",
  "Tailwind",
  "Material-UI",
  "Styled-Components",
  "Figma",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "Premiere Pro",
  "After Effects",
  "Final Cut Pro",
  "Logic Pro X",
  "Pro Tools",
  "Ableton Live",
  "FL Studio",
  "Cubase",
  "Reason",
  "Max",
  "Pure Data",
  "SuperCollider",
  "Sonic Pi",
  "ChucK",
  "TidalCycles",
  "FoxDot",
  "Gibber",
  "Gibberwocky",
  "Web Audio API",
  "Tone.js",
  "p5.js",
  "three.js",
  "A-Frame",
  "Unity",
  "Unreal Engine",
  "Blender",
  "Maya",
  "Cinema 4D",
  "ZBrush",
  "Substance Painter",
  "Substance Designer",
  "Marvelous Designer",
  "Houdini",
  "TouchDesigner",
  "Processing",
  "OpenFrameworks",
  "Cinder",
  "Max",
  "Pure Data",
  "SuperCollider",
  "Sonic Pi",
  "ChucK",
  "TidalCycles",
  "FoxDot",
  "Gibber",
  "Gibberwocky",
  "Web Audio API",
  "Tone.js",
  "p5.js",
  "three.js",
  "A-Frame",
  "Unity",
  "Unreal Engine",
  "Blender",
  "Maya",
];
